### ISSUE TITLE
enable Greenkeeper

### ISSUE THREAD

**Issue by gr2m** [nolanlawson/fsdown#4]
I tried to do it myself but don’t have admin access

**Comment by nolanlawson** [comment]
Oops sorry, I'm not sure why that is. Will fix both things.

**Comment by nolanlawson** [comment]
Huh, not sure how to give you admin access, but I can enable greenkeeper!

**Comment by nolanlawson** [comment]
done

**Comment by gr2m** [comment]
At https://github.com/nolanlawson/fsdown/settings/collaboration, change the Dropdown next to my username from "Write" to "Admin"

**Comment by nolanlawson** [comment]
There's no such option... do you want to just move this repo to an org?

**Comment by gr2m** [comment]
ah okay nevermind me, I didn’t know :) it’s already all setup I think
